<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CurrentOrder.aspx.cs" Inherits="CabManagement.AdminManagement.CurrentOrder" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>
                Current Orders
            </h1>
        </div>
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True"></asp:GridView>
        </div>
    </form>
</body>
</html>
